---
- hosts: "{{ remote_host }}"

  remote_user: "{{ remote_user }}"

  tasks:
  - name: git pull project
    git:
      repo: "{{ git_repo }}"
      dest: "{{ proj_path }}"

  - name: touch wsgi.py
    file:
      path: '{{ wsgi_path }}/wsgi.py'
      state: touch
